targets:
  $default:
    builders:
      extension_theme_generator|text_style:
        generate_for:
          - lib/**/*.dart


builders:
  extension_theme_generator:
    import: "package:extension_theme_generator/builder.dart"
    builder_factories: ["textStyleBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
