targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            .dart:
              - .g.dart
builders:
  text_style_generator:
    import: "package:extension_theme_generator/text_style_generator.dart"
    builder_factories: ["textStyleBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]