targets:
  $default:
    builders:
      extension_theme_generator|text_style:
        options:
          generate_for:
            include:
              - lib/**/*.dart
        enabled: true

builders:
  text_style:
    target: ":"
    import: "package:extension_theme_generator/builder.dart"
    builder_factories: ["textStyleBuilder"]
    build_extensions: {".dart": [".extension_theme_generator.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]