name: extension_theme_generator
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/Kotelnikovekb/extension_theme_generator
author: Yury Kotelnikoff <y@kotelnikoff.expert>

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.3.1
  source_gen: ^1.5.0
  build_runner: ^2.4.11
  analyzer: ^6.4.1


dev_dependencies:
  flutter_lints: ^3.0.0


