name: extension_theme_generator
description: "Code generator for working with extensions in ThemeData"
version: 1.1.2
homepage: https://github.com/Kotelnikovekb/extension_theme_generator

environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  build: ^2.3.1
  source_gen: ^1.5.0
  build_runner: ^2.4.11
  analyzer: ^6.4.1


dev_dependencies:
  flutter_lints: ^3.0.0


